// <auto-generated />
using System;
using IdentityModel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Model.Migrations
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20251124125602_added")]
    partial class added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityModel.Models.IdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedOn")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ModifiedOn")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("IdentityUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1234abcd-1234-1234-1234-ab1234567890"),
                            CreatedBy = "Super User",
                            CreatedOn = 1763818667L,
                            Email = "superuser@email.com",
                            ModifiedBy = "Super User",
                            ModifiedOn = 1763818667L,
                            Name = "Super User",
                            PhoneNumber = "1234",
                            Status = "Active",
                            UserName = ""
                        });
                });

            modelBuilder.Entity("IdentityModel.Models.OtpManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ModifiedOn")
                        .HasColumnType("bigint");

                    b.Property<int>("OneTimePassword")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("OtpManager");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abcd1234-abcd-1234-abcd-1234567890ef"),
                            CreatedBy = "Super User",
                            CreatedOn = new DateTime(1970, 1, 21, 9, 56, 58, 667, DateTimeKind.Utc),
                            IdentityUserId = new Guid("1234abcd-1234-1234-1234-ab1234567890"),
                            IsActive = true,
                            ModifiedBy = "Super User",
                            ModifiedOn = 1763818667L,
                            OneTimePassword = 1234,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("IdentityModel.Models.OtpManager", b =>
                {
                    b.HasOne("IdentityModel.Models.IdentityUser", "IdentityUser")
                        .WithMany("OtpManagers")
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("IdentityModel.Models.IdentityUser", b =>
                {
                    b.Navigation("OtpManagers");
                });
#pragma warning restore 612, 618
        }
    }
}
